application/classes/Controller/Articles/Index.php
application/views/main.php
application/views/templates/articles/article.php
application/views/templates/articles/list.php
application/views/templates/articles/new.php
application/views/templates/index.php
migrations/article_and_comment.sql
public/css/articles.css
public/css/main.css

* новое отображение списка айтемов;
* изменена навигация;
* добавлены новые стили;
* изменён шрифт;
* изменён порядок айтемов.

Изменено отображения списка айтемов

---

application/bootstrap.php
application/tests/classes/SampleTest.php
index.php

Enable unittests
Resolves: #24 (I)

Unit tests basis

---

application/classes/Dao/Articles.php
application/classes/Dao/MySQL/Base.php
application/classes/Model/Article.php
application/classes/Model/User.php
application/views/templates/users/user.php

* Article dao 
* Dao mysql bug fix 
* Article controller moved to dao cached queries 
* User migrated to model. 
Waiting for review from: 
Closes: #26

#26 Article dao.

---

application/classes/Controller/Auth.php
application/classes/Dao/Auth.php
application/tests/classes/SampleTest.php
modules/oauth/classes/Kohana/Oauth/Facebook.php
modules/oauth/classes/Kohana/Oauth/Vkontakte.php

Refactoring oauth module

---

application/views/templates/articles/article.php

Revert "Schemaarticle"

---

application/classes/Controller/Admin.php
application/classes/Model/User.php

Access list #74

---

application/classes/Controller/Articles/Index.php

Throw 404 for article, which doesn't exist
Closes #78

Add 404 for non-existed articles

---

application/classes/HTTP/Exception/403.php
application/views/templates/articles/article.php

Пофикшен баг, разлейте пожалуйста!!
Closes: #76

#76 Fixed central

---

application/views/templates/articles/article.php

корректнаая ссылка на профиль

---

application/classes/Controller/Auth.php

change [] to array() in auth

---

application/classes/Controller/Auth.php

Implement history back redirect after auth

---

application/classes/Controller/Auth.php
application/classes/Model/User.php

Add vk auth

---

application/classes/Controller/Auth.php
application/classes/Model/User.php

Fix user save bug

---

application/views/templates/articles/article.php

Fixed microdata attribute dateModified

DateModified #106

---

application/classes/Controller/Articles/Index.php
application/classes/Model/Article.php
application/classes/Model/Comment.php
application/classes/Model/User.php

add cache to articles, comments-count, user-model

---

application/classes/Controller/Articles/Index.php
application/classes/Controller/Base/preDispatch.php
application/classes/Model/Article.php

Add clear cache for articles

---

.gitignore
application/classes/Controller/Base/preDispatch.php

[issue#104](https://github.com/codex-team/codex/issues/104)
[issue#120](https://github.com/codex-team/codex/issues/120)

add redis, telegram config, remove them from preDispatch

---

.gitignore
application/classes/Model/Methods.php

[issue120](https://github.com/codex-team/codex/issues/120)

move telegram bot config from repo to config-file

---

public/css/main.css

Contest-page mobile-view improve

---

application/classes/Controller/Articles/Action.php
application/classes/Controller/Articles/Index.php
application/classes/Controller/Base/preDispatch.php
application/routes.php
application/views/templates/articles/article.php
application/views/templates/articles/create.php
public/css/main.css

closes #155 
Добавил возможность редактирования и добавления статей
по роутам 
- /article/add
- /article/edit/article_id

simple-editor-#155

---

application/classes/Controller/Articles/Action.php
application/classes/Controller/Articles/Index.php
application/classes/Controller/Contests/Index.php
application/views/templates/articles/create.php

closes #148
- Добавил поле description в поле редактора

meta-description

---

application/views/templates/articles/create.php
application/views/templates/contests/create.php

Bug editor #169

---

modules/oauth/classes/Kohana/Oauth/Github.php

Change parse_str

---

application/classes/Controller/Articles/Index.php
application/classes/Controller/Articles/Modify.php
application/classes/Controller/Users/Index.php
application/classes/Model/Article.php
application/views/templates/articles/create.php
application/views/templates/articles/list.php
application/views/templates/articles/list_wrapper.php
application/views/templates/users/user.php
migrations/2016_05_18_Articles_marked.sql
public/css/main.css

Articles list restyling, articles now appears in users profiles

---

public/css/main.css

Убрать пробел после inline-block элементов

---

application/classes/Controller/Editor.php
application/routes.php
public/extensions/codex.editor/plugins/link/link.css
public/extensions/codex.editor/plugins/link/link.js

Created new action which parses url for link plugin

Added internal route for editor server side.

---

application/views/templates/editor/landing.php
public/js/main.js
public/js/simpleCodeStyling.js

code comments now highlighted

---

application/views/templates/editor/landing.php
public/extensions/codex.editor/codex-editor.js
public/extensions/codex.editor/plugins/header/header.css
public/extensions/codex.editor/plugins/header/header.js
public/extensions/codex.editor/plugins/paragraph/paragraph.css
public/extensions/codex.editor/plugins/paragraph/paragraph.js

Remove initial content, add firstBlock, add placeholders on empty Paragraph or Header

---

application/classes/Controller/Admin.php
application/routes.php
application/views/templates/admin/requests/list.php
application/views/templates/admin/wrapper.php

add page requests

---

.gitignore
application/classes/Controller/Pages.php
application/classes/Model/Methods.php

join-request notification

---

application/views/templates/articles/create.php

- docReady(function() {
+ codex.docReady(function() {

add init class link for docReady

---

migrations/Courses.sql

Migration consist two tables:
- Courses (id, uri, title, description, cover, dt_create, dt_update, is_removed, is_published, marked, order)
-Courses_articles (id, course_id, article_id, article_index)

Tables for courses

---

application/classes/Model/Stats.php

Add check if redis key found. Fix #262

Добавлена проверка на Redis

---

application/classes/Controller/Index.php
application/classes/Model/User.php
application/views/templates/developers.php
application/views/templates/index.php
public/css/codex.css

Now we have TOP CHART

---

application/classes/Model/User.php

Fix bug with model Users getUsersByIds with null results.

---

application/classes/Model/Feed.php
application/views/templates/courses/create.php

Feedlist-bugfix

---

application/classes/Controller/Users/Index.php

Fix error with alias reuse.
Fix error with empty URI redirect.

Fix error with redirect

---

application/classes/Controller/Users/Index.php
application/routes.php

Исправил баг с алиасами

---

application/classes/Controller/Articles/Modify.php
application/routes.php

Article editing route

---

application/views/main.php
application/views/templates/editor/landing.php

Img altered paths fix

---

application/views/templates/landings/codex_bot.php

Bot landing link fix

---

application/classes/Controller/Index.php
application/classes/Model/Methods.php
application/classes/Model/User.php
application/views/templates/articles/article.php
application/views/templates/users/settings.php

JSON Linking Data

---

application/views/templates/join/index.php

Change user photo url on /join page

---

application/classes/Controller/Base/preDispatch.php
application/classes/Controller/Pages.php
application/classes/Controller/Users/Index.php
application/views/main.php
system/classes/Kohana/Controller/Template.php

Add missing descriptions 🦇

---

application/classes/Dao/MySQL/Base.php
application/classes/Model/Article.php

Modify cache keys

---

application/classes/Model/Article.php

Add domain prefix

---

www/application/config/database.php.sample

"Настройка кодировки подключения" on https://ifmo.su/mysql-and-emoji

use mb4 charset

---

www/composer.lock

Update composer dependencies

---

application/classes/Controller/Base/preDispatch.php
application/classes/Dao/MySQL/Base.php
application/classes/Kohana/Exception.php
application/classes/Model/Article.php
application/classes/Model/Stats.php
application/config/cache.php
modules/cache/classes/Cache/Memcached.php
modules/cache/classes/Kohana/Cache/Memcached.php
system/classes/Kohana/Kohana/Exception.php

Мигрируем на PHP7+memcached+mysqli.
TODO: проверить, вероятно обратная совместимость сломается. Используем только в новом докере.

Php7 migration

---

www/application/classes/Controller/Index.php
www/application/classes/Controller/Pages.php
www/application/views/templates/index/index.php
www/application/views/templates/join/index.php

Hide join block on main page and timer on join page

Hide join components

---

www/application/views/templates/admin/articles/feed.php
www/application/views/templates/blocks/share.php
www/application/views/templates/join/index.php
www/application/views/templates/quiz/form.php
www/application/views/templates/quizzes/quiz.php
www/package-lock.json
www/public/app/js/modules/admin.js
www/public/app/js/modules/quiz.js
www/public/app/js/modules/quizForm.js
www/public/app/js/modules/sharer.js
www/public/build/main.bundle.js

Inline scripts calls -> module-dispatcher

Get rid of inline scripts

---

www/application/classes/Controller/Articles/Modify.php
www/application/views/templates/articles/create.php

Don't let to choose current user as coauthor when creating the article

---

www/application/classes/Controller/Articles/Modify.php

Set dt_publish for immediately created articles

---

www/application/classes/Controller/Sitemap.php
www/application/classes/Model/Sitemap.php
www/application/config/system-aliases.php
www/application/routes.php
www/composer.json

Closes #343
Available at url `/sitemap.xml`

Add dynamic sitemap generation

---

www/application/views/templates/landings/editor.php

Grammatical Changes to API is the feature section on editor.js website.
As discussed on issue codex-team/editor.js#677
fixes codex-team/editor.js#677

Grammatical Changes to API is the feature section.

---

www/application/views/templates/landings/editor.php

Update simple-image link

---

www/application/classes/Controller/Index.php
www/application/classes/Controller/Pages.php
www/application/routes.php
www/application/views/templates/index/index.php

Disable `/join` page until next year

Disable join page

---

www/application/routes.php
www/application/views/templates/join/index-en.php
www/application/views/templates/join/index.php

Add "You can still join team" block

Disable /join page enhancement

---

www/application/views/templates/join/index-en.php
www/application/views/templates/join/index.php

Fix name field XSS issue

---

www/modules/oauth/classes/Kohana/Oauth/Github.php

Use auth header instead of request param according to [this](https://developer.github.com/v3/auth/).

Use auth header

---

www/application/classes/Controller/Pages.php
www/application/classes/Model/Methods.php

- remove link tag wrapper for emails
- disable link preview in messages

Upgrade tg notifications

---

docs/development.md
www/application/classes/Controller/Landings.php
www/application/classes/Controller/Sitemap.php
www/application/config/system-aliases.php
www/application/routes.php
www/application/views/templates/landings/lab.php

make page skeleton and basic setup

make codex lab page on /lab

---

www/application/classes/Controller/Base/preDispatch.php

Fix access check

---

www/application/classes/Controller/Articles/Index.php

1. Взято отсюда: https://stackoverflow.com/a/55924961/13001542
2. Если превьюха в телеграме закешировалась, welcome в бота: https://telegram.me/webpagebot

Большие превьюхи для статей

---

.github/CODEOWNERS

Remove codeowners from this repository because I can't merge requests with two approves without approves from all codeowners.

[Feature] Remove codeowners

---

.env.sample
.gitignore
docker-compose.yml
docker/nginx-codex.conf
docker/php/Dockerfile
docs/development.md

Prepare to use in prod

---

www/application/classes/Controller/Articles/Modify.php
www/public/build/release.json

Disable check for CSRF token while saving article

---

www/application/config/editorjs-config.json
www/public/build/release.json

added `withHeadings` data field support for table tool

Chore(config): Update editor config
